"""Migration packaging invariants (G-1350).

Before this, migrations existed twice: the authoritative repo-root `alembic/`
(34 revisions, single head) and a *committed build artifact*
`src/career_os/_alembic/` (24 revisions, stale) that `scripts/build-pip.sh` and
`publish.yml` regenerated by copying at package time. The copy never rewrote
`script_location`, so every built wheel pointed at a non-existent
`career_os/alembic` directory — and `_auto_migrate()` only ever looked for the
repo-root `alembic.ini`, which wheels don't ship. Net effect: `pip install
kestrel-app` silently started on an unmigrated database.

Migrations now live *inside* the package (one copy, shipped via package-data).
These tests pin that: one head, one migrations directory, a packaged config that
resolves, and `_auto_migrate` able to find it without a repo root.
"""

import configparser
import tomllib
from pathlib import Path

from alembic.config import Config
from alembic.script import ScriptDirectory

import career_os

REPO_ROOT = Path(__file__).resolve().parents[1]
PKG_DIR = Path(career_os.__file__).resolve().parent
ROOT_INI = REPO_ROOT / "alembic.ini"
PACKAGED_INI = PKG_DIR / "_alembic.ini"


def _heads(ini_path: Path) -> list[str]:
    return list(ScriptDirectory.from_config(Config(str(ini_path))).get_heads())


def test_single_alembic_head():
    """Multiple heads mean `upgrade head` is ambiguous — keep the chain linear."""
    heads = _heads(ROOT_INI)
    assert len(heads) == 1, f"expected exactly one alembic head, got {heads}"


def test_migrations_live_inside_the_package():
    """One copy only: the old repo-root `alembic/` must not come back.

    A second directory is what allowed the shipped copy to drift 10 revisions
    behind without anything failing.
    """
    assert (PKG_DIR / "_alembic" / "versions").is_dir()
    assert not (REPO_ROOT / "alembic").exists(), (
        "repo-root alembic/ reappeared — migrations must live only in "
        "src/career_os/_alembic so the wheel and the repo can't diverge (G-1350)."
    )


def test_packaged_config_exists_and_resolves_to_the_same_head():
    """An installed wheel must migrate to exactly the schema the repo expects."""
    assert PACKAGED_INI.is_file(), f"packaged alembic config missing: {PACKAGED_INI}"
    assert _heads(PACKAGED_INI) == _heads(ROOT_INI)


def test_packaged_config_script_location_points_at_the_package():
    """The bug that shipped: the copied ini kept `%(here)s/alembic` (nonexistent)."""
    # interpolation=None: alembic's `%(here)s` is not configparser interpolation
    parser = configparser.ConfigParser(interpolation=None)
    parser.read(PACKAGED_INI)
    script_location = parser["alembic"]["script_location"]
    assert script_location == "%(here)s/_alembic", script_location
    resolved = PACKAGED_INI.parent / script_location.replace("%(here)s/", "")
    assert resolved.is_dir(), f"script_location does not resolve: {resolved}"


def test_auto_migrate_can_find_a_config_without_a_repo_root():
    """`_auto_migrate` looks for `<package>/_alembic.ini` last — it must be there.

    That candidate is the only one present in an installed wheel (no CWD
    alembic.ini, no repo root), so if it goes missing, installs silently skip
    migrations again.
    """
    from career_os import main as main_module

    source = Path(main_module.__file__).read_text(encoding="utf-8")
    assert "_alembic.ini" in source, "_auto_migrate no longer falls back to the packaged config"
    assert PACKAGED_INI.is_file()


def test_package_data_ships_the_migrations():
    """Guards the wheel: package-data must include the migrations and the config."""
    with open(REPO_ROOT / "pyproject.toml", "rb") as fh:
        pyproject = tomllib.load(fh)
    patterns = pyproject["tool"]["setuptools"]["package-data"]["career_os"]
    for required in ("_alembic/versions/*.py", "_alembic/*.py", "_alembic.ini"):
        assert required in patterns, f"pyproject package-data missing {required!r}"


def test_no_build_time_migration_copy_remains():
    """The copy step is what drifted — it must stay gone from both build paths."""
    for rel in ("scripts/build-pip.sh", ".github/workflows/publish.yml"):
        text = (REPO_ROOT / rel).read_text(encoding="utf-8")
        assert "cp -r alembic " not in text and 'cp -r "$ROOT/alembic"' not in text, (
            f"{rel} still copies alembic into the package — migrations are committed "
            f"in src/career_os/_alembic now (G-1350)."
        )
