"""Migration packaging invariants (G-1350).

Before this, migrations existed twice: the authoritative repo-root `alembic/`
(34 revisions, single head) and a *committed build artifact*
`src/career_os/_alembic/` (24 revisions, stale) that `scripts/build-pip.sh` and
`publish.yml` regenerated by copying at package time. The copy never rewrote
`script_location`, so every built wheel pointed at a non-existent
`career_os/alembic` directory — and `_auto_migrate()` only ever looked for the
repo-root `alembic.ini`, which wheels don't ship. Net effect: `pip install
kestrel-app` silently started on an unmigrated database.

Migrations now live *inside* the package (one copy, shipped via package-data).
These tests pin that: one head, one migrations directory, a packaged config that
resolves, and `_auto_migrate` able to find it without a repo root.
"""

import configparser
import tomllib
from pathlib import Path

from alembic.config import Config
from alembic.script import ScriptDirectory

import career_os

REPO_ROOT = Path(__file__).resolve().parents[1]
PKG_DIR = Path(career_os.__file__).resolve().parent
ROOT_INI = REPO_ROOT / "alembic.ini"
PACKAGED_INI = PKG_DIR / "_alembic.ini"


def _heads(ini_path: Path) -> list[str]:
    return list(ScriptDirectory.from_config(Config(str(ini_path))).get_heads())


def test_single_alembic_head():
    """Multiple heads mean `upgrade head` is ambiguous — keep the chain linear."""
    heads = _heads(ROOT_INI)
    assert len(heads) == 1, f"expected exactly one alembic head, got {heads}"


def test_migrations_live_inside_the_package():
    """One copy only: the old repo-root `alembic/` must not come back.

    A second directory is what allowed the shipped copy to drift 10 revisions
    behind without anything failing.
    """
    assert (PKG_DIR / "_alembic" / "versions").is_dir()
    assert not (REPO_ROOT / "alembic").exists(), (
        "repo-root alembic/ reappeared — migrations must live only in "
        "src/career_os/_alembic so the wheel and the repo can't diverge (G-1350)."
    )


def test_packaged_config_exists_and_resolves_to_the_same_head():
    """An installed wheel must migrate to exactly the schema the repo expects."""
    assert PACKAGED_INI.is_file(), f"packaged alembic config missing: {PACKAGED_INI}"
    assert _heads(PACKAGED_INI) == _heads(ROOT_INI)


def test_packaged_config_script_location_points_at_the_package():
    """The bug that shipped: the copied ini kept `%(here)s/alembic` (nonexistent)."""
    # interpolation=None: alembic's `%(here)s` is not configparser interpolation
    parser = configparser.ConfigParser(interpolation=None)
    parser.read(PACKAGED_INI)
    script_location = parser["alembic"]["script_location"]
    assert script_location == "%(here)s/_alembic", script_location
    resolved = PACKAGED_INI.parent / script_location.replace("%(here)s/", "")
    assert resolved.is_dir(), f"script_location does not resolve: {resolved}"


def test_resolve_alembic_ini_falls_back_to_packaged_config(tmp_path):
    """Behavioral: with no CWD config and no repo root, the packaged ini wins.

    This simulates an installed wheel — the review of the first version of this
    test proved a source-grep was vacuous (the string it looked for also appears
    in a comment), so this exercises the real resolution path instead.
    """
    from career_os.main import _resolve_alembic_ini

    # fake installed layout: site-packages/career_os/_alembic.ini
    site = tmp_path / "site-packages"
    pkg = site / "career_os"
    pkg.mkdir(parents=True)
    packaged = pkg / "_alembic.ini"
    packaged.write_text(PACKAGED_INI.read_text(encoding="utf-8"), encoding="utf-8")
    bare_cwd = tmp_path / "somewhere-else"
    bare_cwd.mkdir()

    resolved = _resolve_alembic_ini(pkg_dir=pkg, cwd=bare_cwd)
    assert resolved == packaged

    # ...and with the packaged config gone, it must REFUSE to start, not skip
    packaged.unlink()
    import pytest as _pytest

    with _pytest.raises(RuntimeError, match="refusing to start"):
        _resolve_alembic_ini(pkg_dir=pkg, cwd=bare_cwd)


def test_resolve_alembic_ini_prefers_cwd_then_repo_root(tmp_path):
    """Resolution order: CWD (Docker) -> repo root (checkout) -> packaged (wheel)."""
    from career_os.main import _resolve_alembic_ini

    pkg = tmp_path / "repo" / "src" / "career_os"
    pkg.mkdir(parents=True)
    repo_ini = tmp_path / "repo" / "alembic.ini"
    repo_ini.write_text("[alembic]\n", encoding="utf-8")
    cwd = tmp_path / "cwd"
    cwd.mkdir()
    cwd_ini = cwd / "alembic.ini"
    cwd_ini.write_text("[alembic]\n", encoding="utf-8")

    assert _resolve_alembic_ini(pkg_dir=pkg, cwd=cwd) == cwd_ini
    cwd_ini.unlink()
    assert _resolve_alembic_ini(pkg_dir=pkg, cwd=cwd) == repo_ini


def test_root_and_packaged_configs_agree_except_script_location():
    """The two inis must stay in lockstep — only `script_location` may differ.

    Two hand-synced copies are the failure mode this PR retired; if
    `sqlalchemy.url`, `file_template`, or logging config drifts between them, an
    installed wheel migrates differently than a checkout (review WR-7).
    """
    import configparser

    def load(path: Path) -> configparser.ConfigParser:
        parser = configparser.ConfigParser(interpolation=None)
        parser.read(path)
        return parser

    root, packaged = load(ROOT_INI), load(PACKAGED_INI)
    assert set(root.sections()) == set(packaged.sections())
    for section in root.sections():
        keys = set(root[section]) | set(packaged[section])
        for key in keys:
            if section == "alembic" and key == "script_location":
                continue
            assert root[section].get(key) == packaged[section].get(key), (
                f"[{section}] {key} differs between alembic.ini and the packaged "
                f"_alembic.ini — keep them identical except script_location (G-1350)."
            )


def test_package_data_ships_the_migrations():
    """Guards the wheel: package-data must include the migrations and the config."""
    with open(REPO_ROOT / "pyproject.toml", "rb") as fh:
        pyproject = tomllib.load(fh)
    patterns = pyproject["tool"]["setuptools"]["package-data"]["career_os"]
    for required in ("_alembic/versions/*.py", "_alembic/*.py", "_alembic.ini"):
        assert required in patterns, f"pyproject package-data missing {required!r}"


def test_no_build_time_migration_copy_remains():
    """The copy step is what drifted — it must stay gone from both build paths.

    Asserts on `_alembic` appearing as a copy *destination* rather than matching
    exact `cp -r alembic` strings (review WR-8: `cp -a`, `rsync`, `./alembic`, or
    re-adding the `cp alembic.ini src/career_os/_alembic.ini` half would have
    slipped past a literal match).
    """
    import re

    copy_dest = re.compile(
        r"\b(?:cp|rsync|install)\b[^\n]*\b(?:src/career_os/_alembic|\$\w+/_alembic|_alembic\.ini)",
    )
    for rel in ("scripts/build-pip.sh", ".github/workflows/publish.yml"):
        text = (REPO_ROOT / rel).read_text(encoding="utf-8")
        hits = [
            line.strip()
            for line in text.splitlines()
            if copy_dest.search(line) and not line.strip().startswith("#")
        ]
        assert not hits, (
            f"{rel} writes into the packaged _alembic at build time: {hits} — "
            f"migrations are committed in src/career_os/_alembic; nothing may "
            f"regenerate them (G-1350)."
        )


def test_migrated_schema_matches_model_metadata(tmp_path):
    """`alembic upgrade head` must produce exactly the tables the models declare.

    This is the gap that let `warn_filings` go missing from every migrated
    database while `models/warn.py`, `cli/warn.py` and the WARN red-flag rule all
    queried it (G-1350). Nothing else catches it: `tests/conftest.py` builds the
    test schema with `Base.metadata.create_all`, so the table always exists under
    pytest, and CI only asserts that `alembic upgrade head` *runs*.

    Note the deliberate `pkgutil` sweep — `career_os.models.__init__` does not
    import every model module, so a plain `import career_os.models` silently
    under-counts the expected tables (which is exactly how this was missed).
    """
    import importlib
    import pkgutil
    import sqlite3

    from alembic import command

    import career_os.models as models_pkg
    from career_os.database import Base

    for module in pkgutil.iter_modules(models_pkg.__path__):
        importlib.import_module(f"career_os.models.{module.name}")

    db_path = tmp_path / "schema_check.db"
    # Config built programmatically, NOT from the ini file: env.py only calls
    # fileConfig() when config_file_name is set, and fileConfig globally disables
    # existing loggers — which silently broke five unrelated caplog-based tests
    # further down the suite when this test loaded the real ini.
    cfg = Config()
    cfg.set_main_option("script_location", str(PKG_DIR / "_alembic"))
    cfg.set_main_option("sqlalchemy.url", f"sqlite:///{db_path}")
    command.upgrade(cfg, "head")

    with sqlite3.connect(db_path) as con:
        migrated = {
            row[0] for row in con.execute("SELECT name FROM sqlite_master WHERE type='table'")
        }
    declared = set(Base.metadata.tables)

    missing = sorted(declared - migrated)
    assert not missing, (
        f"table(s) {missing} are declared in Base.metadata but no migration creates "
        f"them — a migrated deployment will fail at runtime on any query against "
        f"them (G-1350)."
    )
