"""Pydantic schemas package."""

from career_os.schemas.ai import AICompleteRequest, AIFeature, AIResponse
from career_os.schemas.applications import (
    ActivityLogResponse,
    ApplicationCreate,
    ApplicationDetailResponse,
    ApplicationListResponse,
    ApplicationResponse,
    ApplicationStatus,
    ApplicationUpdate,
)
from career_os.schemas.gaps import (
    AggregateGapItem,
    AggregateGapResponse,
    GapAnalysisResponse,
    GapItem,
    GapSeverity,
    JobRequirementBulkCreate,
    JobRequirementCreate,
    JobRequirementResponse,
)
from career_os.schemas.goals import (
    AlternativePath,
    AlternativesResponse,
    GoalCreate,
    GoalListResponse,
    GoalResponse,
    GoalStatus,
    GoalType,
    GoalUpdate,
    ProgressDimension,
    ProgressResponse,
    RealityMapDimension,
    RealityMapResponse,
    RecalibrationResponse,
)
from career_os.schemas.profiles import ProfileListResponse, ProfileResponse
from career_os.schemas.research import (
    CompanyResearchReport,
    CompanyResearchRequest,
    FundingReport,
    GlassdoorReport,
    HiringPatternsReport,
    SourceWarning,
    TechStackReport,
    ValuesAlignmentReport,
)
from career_os.schemas.skills import (
    IngestRequest,
    IngestResponse,
    SkillCategory,
    SkillCreate,
    SkillHistoryResponse,
    SkillListResponse,
    SkillProficiency,
    SkillResponse,
    SkillsEmptyStateResponse,
    SkillUpdate,
)

__all__ = [
    "AICompleteRequest",
    "AIFeature",
    "AIResponse",
    "ActivityLogResponse",
    "AggregateGapItem",
    "AggregateGapResponse",
    "AlternativePath",
    "AlternativesResponse",
    "ApplicationCreate",
    "ApplicationDetailResponse",
    "ApplicationListResponse",
    "ApplicationResponse",
    "ApplicationStatus",
    "ApplicationUpdate",
    "GapAnalysisResponse",
    "GapItem",
    "GapSeverity",
    "GoalCreate",
    "GoalListResponse",
    "GoalResponse",
    "GoalStatus",
    "GoalType",
    "GoalUpdate",
    "IngestRequest",
    "IngestResponse",
    "JobRequirementBulkCreate",
    "JobRequirementCreate",
    "JobRequirementResponse",
    "ProfileListResponse",
    "ProfileResponse",
    "ProgressDimension",
    "ProgressResponse",
    "RealityMapDimension",
    "RealityMapResponse",
    "RecalibrationResponse",
    "SkillCategory",
    "SkillCreate",
    "SkillHistoryResponse",
    "SkillListResponse",
    "SkillProficiency",
    "SkillResponse",
    "SkillsEmptyStateResponse",
    "SkillUpdate",
    "CompanyResearchReport",
    "CompanyResearchRequest",
    "FundingReport",
    "GlassdoorReport",
    "HiringPatternsReport",
    "SourceWarning",
    "TechStackReport",
    "ValuesAlignmentReport",
]
