"""add saved_searches table

Revision ID: 07cca291f71f
Revises: e8b54d7d5d6a
Create Date: 2026-03-13 21:30:04.969376

"""

from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "07cca291f71f"
down_revision: Union[str, Sequence[str], None] = "e8b54d7d5d6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saved_searches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("config", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("saved_searches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_saved_searches_profile_id"), ["profile_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("saved_searches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_saved_searches_profile_id"))

    op.drop_table("saved_searches")
    # ### end Alembic commands ###
