"""add discovery models: discovered_jobs, search_profiles, discovery_runs

Revision ID: 775c5d68cc2d
Revises: b192ca99adc9
Create Date: 2026-03-13 20:57:12.532122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775c5d68cc2d'
down_revision: Union[str, Sequence[str], None] = 'b192ca99adc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('locations', sa.Text(), nullable=True),
    sa.Column('remote_only', sa.Boolean(), nullable=False),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('filters', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_profiles_profile_id'), ['profile_id'], unique=False)

    op.create_table('discovered_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('salary_range', sa.String(length=255), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title_normalized', sa.String(length=500), nullable=False),
    sa.Column('company_normalized', sa.String(length=255), nullable=False),
    sa.Column('location_normalized', sa.String(length=255), nullable=False),
    sa.Column('sources', sa.Text(), nullable=False),
    sa.Column('source_urls', sa.Text(), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_normalized', 'company_normalized', 'location_normalized', name='uq_discovered_job_dedup')
    )
    with op.batch_alter_table('discovered_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovered_jobs_company_normalized'), ['company_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_jobs_location_normalized'), ['location_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_jobs_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_discovered_jobs_title_normalized'), ['title_normalized'], unique=False)

    op.create_table('discovery_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('search_profile_id', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_found', sa.Integer(), nullable=False),
    sa.Column('new_jobs', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['search_profile_id'], ['search_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovery_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovery_runs_profile_id'), ['profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discovery_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovery_runs_profile_id'))

    op.drop_table('discovery_runs')
    with op.batch_alter_table('discovered_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovered_jobs_title_normalized'))
        batch_op.drop_index(batch_op.f('ix_discovered_jobs_profile_id'))
        batch_op.drop_index(batch_op.f('ix_discovered_jobs_location_normalized'))
        batch_op.drop_index(batch_op.f('ix_discovered_jobs_company_normalized'))

    op.drop_table('discovered_jobs')
    with op.batch_alter_table('search_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_profiles_profile_id'))

    op.drop_table('search_profiles')
    # ### end Alembic commands ###
