"""add_onboarding_states_table

Revision ID: e68f373345cd
Revises: p7q8r9s0t1u2
Create Date: 2026-04-20 13:43:10.531337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68f373345cd'
down_revision: Union[str, Sequence[str], None] = 'p7q8r9s0t1u2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esco_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concept_uri', sa.String(length=500), nullable=False),
    sa.Column('preferred_label', sa.String(length=500), nullable=False),
    sa.Column('alt_labels', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skill_type', sa.String(length=100), nullable=True),
    sa.Column('isco_group', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('esco_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_esco_skills_concept_uri'), ['concept_uri'], unique=True)
        batch_op.create_index(batch_op.f('ix_esco_skills_preferred_label'), ['preferred_label'], unique=False)

    op.create_table('skill_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_text', sa.String(length=500), nullable=False),
    sa.Column('esco_uri', sa.String(length=500), nullable=True),
    sa.Column('preferred_label', sa.String(length=500), nullable=True),
    sa.Column('match_method', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_text', name='uq_skill_mappings_raw_text')
    )
    with op.batch_alter_table('skill_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_mappings_raw_text'), ['raw_text'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('referral_status', sa.String(length=50), nullable=True),
    sa.Column('warmth', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_follow_up', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_profile_id'), ['profile_id'], unique=False)

    op.create_table('onboarding_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('profile_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('demo_seeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('welcome_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tour_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feedback_prompted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_started_via', sa.String(length=10), nullable=True),
    sa.Column('profile_completed_via', sa.String(length=10), nullable=True),
    sa.Column('demo_seeded_via', sa.String(length=10), nullable=True),
    sa.Column('welcome_completed_via', sa.String(length=10), nullable=True),
    sa.Column('tour_completed_via', sa.String(length=10), nullable=True),
    sa.Column('feedback_prompted_via', sa.String(length=10), nullable=True),
    sa.Column('completed_via', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onboarding_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_states_profile_id'), ['profile_id'], unique=True)

    op.create_table('contact_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_applications_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_applications_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_applications_profile_id'), ['profile_id'], unique=False)

    op.create_table('contact_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_interactions_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_interactions_profile_id'), ['profile_id'], unique=False)

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('entity_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duration_ms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('metadata', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_activity_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_entity_type'), ['entity_type'], unique=False)

    with op.batch_alter_table('job_requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('esco_uri', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_job_requirements_esco_uri'), ['esco_uri'], unique=False)

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('esco_uri', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_skills_esco_uri'), ['esco_uri'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_esco_uri'))
        batch_op.drop_column('esco_uri')

    with op.batch_alter_table('job_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_requirements_esco_uri'))
        batch_op.drop_column('esco_uri')

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_activity_log_entity_id'))
        batch_op.drop_column('metadata')
        batch_op.drop_column('error')
        batch_op.drop_column('duration_ms')
        batch_op.drop_column('entity_id')
        batch_op.drop_column('entity_type')

    with op.batch_alter_table('contact_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_interactions_profile_id'))
        batch_op.drop_index(batch_op.f('ix_contact_interactions_contact_id'))

    op.drop_table('contact_interactions')
    with op.batch_alter_table('contact_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_applications_profile_id'))
        batch_op.drop_index(batch_op.f('ix_contact_applications_contact_id'))
        batch_op.drop_index(batch_op.f('ix_contact_applications_application_id'))

    op.drop_table('contact_applications')
    with op.batch_alter_table('onboarding_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onboarding_states_profile_id'))

    op.drop_table('onboarding_states')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_profile_id'))

    op.drop_table('contacts')
    with op.batch_alter_table('skill_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_mappings_raw_text'))

    op.drop_table('skill_mappings')
    with op.batch_alter_table('esco_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_esco_skills_preferred_label'))
        batch_op.drop_index(batch_op.f('ix_esco_skills_concept_uri'))

    op.drop_table('esco_skills')
    # ### end Alembic commands ###
