"""add scoring engine models scoring_weights scored_jobs

Revision ID: e8b54d7d5d6a
Revises: 775c5d68cc2d
Create Date: 2026-03-13 21:09:08.335044

"""

from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8b54d7d5d6a"
down_revision: Union[str, Sequence[str], None] = "775c5d68cc2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scoring_weights",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("skills_match", sa.Float(), nullable=False),
        sa.Column("career_alignment", sa.Float(), nullable=False),
        sa.Column("culture_fit", sa.Float(), nullable=False),
        sa.Column("salary_match", sa.Float(), nullable=False),
        sa.Column("location_match", sa.Float(), nullable=False),
        sa.Column("growth_potential", sa.Float(), nullable=False),
        sa.Column("remote_preference", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scoring_weights", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scoring_weights_profile_id"), ["profile_id"], unique=True
        )

    op.create_table(
        "scored_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("discovered_job_id", sa.Integer(), nullable=True),
        sa.Column("application_id", sa.Integer(), nullable=True),
        sa.Column("fit_score", sa.Float(), nullable=False),
        sa.Column("readiness_score", sa.Float(), nullable=False),
        sa.Column("career_alignment", sa.Float(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("estimated_salary", sa.String(length=255), nullable=True),
        sa.Column("effort_flag", sa.String(length=50), nullable=False),
        sa.Column("prep_level", sa.String(length=50), nullable=False),
        sa.Column("prep_notes", sa.Text(), nullable=True),
        sa.Column("is_stale", sa.Boolean(), nullable=False),
        sa.Column("weights_snapshot", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["discovered_job_id"],
            ["discovered_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scored_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scored_jobs_application_id"), ["application_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_scored_jobs_discovered_job_id"), ["discovered_job_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_scored_jobs_profile_id"), ["profile_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("scored_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scored_jobs_profile_id"))
        batch_op.drop_index(batch_op.f("ix_scored_jobs_discovered_job_id"))
        batch_op.drop_index(batch_op.f("ix_scored_jobs_application_id"))

    op.drop_table("scored_jobs")
    with op.batch_alter_table("scoring_weights", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scoring_weights_profile_id"))

    op.drop_table("scoring_weights")
    # ### end Alembic commands ###
